USE SAKILA;

SELECT TITLE, SPECIAL_FEATURES
FROM FILM AS F
WHERE RATING = 'PG-13';

SELECT LENGTH, COUNT(*) AS CANTIDAD
FROM FILM
GROUP BY LENGTH;

SELECT TITLE, RENTAL_RATE, REPLACEMENT_COST
FROM FILM
WHERE REPLACEMENT_COST BETWEEN 20 AND 24;

SELECT TITLE, C.NAME, RATING
FROM FILM
         INNER JOIN FILM_CATEGORY FC ON FILM.FILM_ID = FC.FILM_ID
         INNER JOIN CATEGORY C ON FC.CATEGORY_ID = C.CATEGORY_ID
WHERE SPECIAL_FEATURES LIKE '%BEHIND THE SCENES%';

SELECT FIRST_NAME, LAST_NAME
FROM ACTOR
         INNER JOIN FILM_ACTOR FA ON ACTOR.ACTOR_ID = FA.ACTOR_ID
         INNER JOIN FILM F ON FA.FILM_ID = F.FILM_ID
WHERE F.TITLE = 'ZOOLANDER FICTION';

SELECT ADDRESS, CITY, COUNTRY
FROM STORE
         INNER JOIN ADDRESS A ON STORE.ADDRESS_ID = A.ADDRESS_ID
         INNER JOIN CITY C ON A.CITY_ID = C.CITY_ID
         INNER JOIN COUNTRY COUN ON C.COUNTRY_ID = COUN.COUNTRY_ID
WHERE STORE_ID = 1;

SELECT FILM1.TITLE, FILM2.TITLE
FROM FILM AS FILM1,
     FILM AS FILM2
WHERE FILM1.RATING = FILM2.RATING
  AND FILM1.FILM_ID != FILM2.FILM_ID;

SELECT TITLE, S2.FIRST_NAME, S2.LAST_NAME
FROM FILM
         INNER JOIN INVENTORY I ON FILM.FILM_ID = I.FILM_ID
         INNER JOIN STORE S ON I.STORE_ID = S.STORE_ID
         INNER JOIN STAFF S2 ON S.MANAGER_STAFF_ID = S2.STAFF_ID
WHERE I.STORE_ID = 2;

